// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for cockroachdb metrics.
type MetricsConfig struct {
	CockroachdbClusterLocksCount             MetricConfig `mapstructure:"cockroachdb.cluster.locks.count"`
	CockroachdbClusterQueriesActive          MetricConfig `mapstructure:"cockroachdb.cluster.queries.active"`
	CockroachdbClusterSessionsActive         MetricConfig `mapstructure:"cockroachdb.cluster.sessions.active"`
	CockroachdbClusterTransactionsActive     MetricConfig `mapstructure:"cockroachdb.cluster.transactions.active"`
	CockroachdbContentionEventsTotal         MetricConfig `mapstructure:"cockroachdb.contention.events.total"`
	CockroachdbIndexContentionEvents         MetricConfig `mapstructure:"cockroachdb.index.contention.events"`
	CockroachdbIndexReadsTotal               MetricConfig `mapstructure:"cockroachdb.index.reads.total"`
	CockroachdbJobsCount                     MetricConfig `mapstructure:"cockroachdb.jobs.count"`
	CockroachdbNodesLive                     MetricConfig `mapstructure:"cockroachdb.nodes.live"`
	CockroachdbNodesTotal                    MetricConfig `mapstructure:"cockroachdb.nodes.total"`
	CockroachdbRangesTotal                   MetricConfig `mapstructure:"cockroachdb.ranges.total"`
	CockroachdbRangesUnavailable             MetricConfig `mapstructure:"cockroachdb.ranges.unavailable"`
	CockroachdbRangesUnderReplicated         MetricConfig `mapstructure:"cockroachdb.ranges.under_replicated"`
	CockroachdbSchemaChangesActive           MetricConfig `mapstructure:"cockroachdb.schema_changes.active"`
	CockroachdbSessionMemoryAllocated        MetricConfig `mapstructure:"cockroachdb.session.memory.allocated"`
	CockroachdbStatementBytesReadMean        MetricConfig `mapstructure:"cockroachdb.statement.bytes.read.mean"`
	CockroachdbStatementErrorCount           MetricConfig `mapstructure:"cockroachdb.statement.error.count"`
	CockroachdbStatementExecutionCount       MetricConfig `mapstructure:"cockroachdb.statement.execution.count"`
	CockroachdbStatementLatencyParseMean     MetricConfig `mapstructure:"cockroachdb.statement.latency.parse.mean"`
	CockroachdbStatementLatencyPlanMean      MetricConfig `mapstructure:"cockroachdb.statement.latency.plan.mean"`
	CockroachdbStatementLatencyRunMean       MetricConfig `mapstructure:"cockroachdb.statement.latency.run.mean"`
	CockroachdbStatementLatencyServiceMean   MetricConfig `mapstructure:"cockroachdb.statement.latency.service.mean"`
	CockroachdbStatementRetriesMax           MetricConfig `mapstructure:"cockroachdb.statement.retries.max"`
	CockroachdbStatementRowsReadMean         MetricConfig `mapstructure:"cockroachdb.statement.rows.read.mean"`
	CockroachdbStatementRowsWrittenMean      MetricConfig `mapstructure:"cockroachdb.statement.rows.written.mean"`
	CockroachdbTableContentionEvents         MetricConfig `mapstructure:"cockroachdb.table.contention.events"`
	CockroachdbTransactionBytesReadMean      MetricConfig `mapstructure:"cockroachdb.transaction.bytes.read.mean"`
	CockroachdbTransactionExecutionCount     MetricConfig `mapstructure:"cockroachdb.transaction.execution.count"`
	CockroachdbTransactionLatencyCommitMean  MetricConfig `mapstructure:"cockroachdb.transaction.latency.commit.mean"`
	CockroachdbTransactionLatencyRetryMean   MetricConfig `mapstructure:"cockroachdb.transaction.latency.retry.mean"`
	CockroachdbTransactionLatencyServiceMean MetricConfig `mapstructure:"cockroachdb.transaction.latency.service.mean"`
	CockroachdbTransactionRetriesMax         MetricConfig `mapstructure:"cockroachdb.transaction.retries.max"`
	CockroachdbTransactionRowsReadMean       MetricConfig `mapstructure:"cockroachdb.transaction.rows.read.mean"`
	CockroachdbTransactionRowsWrittenMean    MetricConfig `mapstructure:"cockroachdb.transaction.rows.written.mean"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		CockroachdbClusterLocksCount: MetricConfig{
			Enabled: true,
		},
		CockroachdbClusterQueriesActive: MetricConfig{
			Enabled: true,
		},
		CockroachdbClusterSessionsActive: MetricConfig{
			Enabled: true,
		},
		CockroachdbClusterTransactionsActive: MetricConfig{
			Enabled: true,
		},
		CockroachdbContentionEventsTotal: MetricConfig{
			Enabled: true,
		},
		CockroachdbIndexContentionEvents: MetricConfig{
			Enabled: true,
		},
		CockroachdbIndexReadsTotal: MetricConfig{
			Enabled: true,
		},
		CockroachdbJobsCount: MetricConfig{
			Enabled: true,
		},
		CockroachdbNodesLive: MetricConfig{
			Enabled: false,
		},
		CockroachdbNodesTotal: MetricConfig{
			Enabled: false,
		},
		CockroachdbRangesTotal: MetricConfig{
			Enabled: false,
		},
		CockroachdbRangesUnavailable: MetricConfig{
			Enabled: false,
		},
		CockroachdbRangesUnderReplicated: MetricConfig{
			Enabled: false,
		},
		CockroachdbSchemaChangesActive: MetricConfig{
			Enabled: true,
		},
		CockroachdbSessionMemoryAllocated: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementBytesReadMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementErrorCount: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementExecutionCount: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementLatencyParseMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementLatencyPlanMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementLatencyRunMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementLatencyServiceMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementRetriesMax: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementRowsReadMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbStatementRowsWrittenMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTableContentionEvents: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionBytesReadMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionExecutionCount: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionLatencyCommitMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionLatencyRetryMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionLatencyServiceMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionRetriesMax: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionRowsReadMean: MetricConfig{
			Enabled: true,
		},
		CockroachdbTransactionRowsWrittenMean: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for cockroachdb resource attributes.
type ResourceAttributesConfig struct {
	DbSystemName ResourceAttributeConfig `mapstructure:"db.system.name"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		DbSystemName: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for cockroachdb metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
