// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbClusterLocksCountDataPoint(ts, 1, "database-val", "table-val", "lock_strength-val", "granted-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbClusterQueriesActiveDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbClusterSessionsActiveDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbClusterTransactionsActiveDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbContentionEventsTotalDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbIndexContentionEventsDataPoint(ts, 1, "database-val", "schema-val", "table-val", "index-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbIndexReadsTotalDataPoint(ts, 1, "table-val", "index-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbJobsCountDataPoint(ts, 1, "job_type-val", "status-val")

			allMetricsCount++
			mb.RecordCockroachdbNodesLiveDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordCockroachdbNodesTotalDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordCockroachdbRangesTotalDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordCockroachdbRangesUnavailableDataPoint(ts, 1)

			allMetricsCount++
			mb.RecordCockroachdbRangesUnderReplicatedDataPoint(ts, 1)

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbSchemaChangesActiveDataPoint(ts, 1, "table-val", "change_type-val", "state-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbSessionMemoryAllocatedDataPoint(ts, 1, "node_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementBytesReadMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementErrorCountDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val", "last_error_code-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementExecutionCountDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "database-val", "query-val", "statement_type-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementLatencyParseMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementLatencyPlanMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementLatencyRunMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementLatencyServiceMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementRetriesMaxDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementRowsReadMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbStatementRowsWrittenMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val", "query-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTableContentionEventsDataPoint(ts, 1, "database-val", "schema-val", "table-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionBytesReadMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionExecutionCountDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionLatencyCommitMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionLatencyRetryMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionLatencyServiceMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionRetriesMaxDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionRowsReadMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordCockroachdbTransactionRowsWrittenMeanDataPoint(ts, 1, "fingerprint_id-val", "app_name-val")

			rb := mb.NewResourceBuilder()
			rb.SetDbSystemNameCockroachdb()
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "cockroachdb.cluster.locks.count":
					assert.False(t, validatedMetrics["cockroachdb.cluster.locks.count"], "Found a duplicate in the metrics slice: cockroachdb.cluster.locks.count")
					validatedMetrics["cockroachdb.cluster.locks.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of locks grouped by database, table, strength, and grant status.", ms.At(i).Description())
					assert.Equal(t, "{locks}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("table")
					assert.True(t, ok)
					assert.Equal(t, "table-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("lock_strength")
					assert.True(t, ok)
					assert.Equal(t, "lock_strength-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("granted")
					assert.True(t, ok)
					assert.Equal(t, "granted-val", attrVal.Str())
				case "cockroachdb.cluster.queries.active":
					assert.False(t, validatedMetrics["cockroachdb.cluster.queries.active"], "Found a duplicate in the metrics slice: cockroachdb.cluster.queries.active")
					validatedMetrics["cockroachdb.cluster.queries.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of currently active queries.", ms.At(i).Description())
					assert.Equal(t, "{queries}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.cluster.sessions.active":
					assert.False(t, validatedMetrics["cockroachdb.cluster.sessions.active"], "Found a duplicate in the metrics slice: cockroachdb.cluster.sessions.active")
					validatedMetrics["cockroachdb.cluster.sessions.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active sessions.", ms.At(i).Description())
					assert.Equal(t, "{sessions}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.cluster.transactions.active":
					assert.False(t, validatedMetrics["cockroachdb.cluster.transactions.active"], "Found a duplicate in the metrics slice: cockroachdb.cluster.transactions.active")
					validatedMetrics["cockroachdb.cluster.transactions.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active transactions.", ms.At(i).Description())
					assert.Equal(t, "{transactions}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.contention.events.total":
					assert.False(t, validatedMetrics["cockroachdb.contention.events.total"], "Found a duplicate in the metrics slice: cockroachdb.contention.events.total")
					validatedMetrics["cockroachdb.contention.events.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total contention events across all tables and indexes.", ms.At(i).Description())
					assert.Equal(t, "{events}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.index.contention.events":
					assert.False(t, validatedMetrics["cockroachdb.index.contention.events"], "Found a duplicate in the metrics slice: cockroachdb.index.contention.events")
					validatedMetrics["cockroachdb.index.contention.events"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of contention events on an index.", ms.At(i).Description())
					assert.Equal(t, "{events}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("schema")
					assert.True(t, ok)
					assert.Equal(t, "schema-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("table")
					assert.True(t, ok)
					assert.Equal(t, "table-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("index")
					assert.True(t, ok)
					assert.Equal(t, "index-val", attrVal.Str())
				case "cockroachdb.index.reads.total":
					assert.False(t, validatedMetrics["cockroachdb.index.reads.total"], "Found a duplicate in the metrics slice: cockroachdb.index.reads.total")
					validatedMetrics["cockroachdb.index.reads.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total number of reads from an index.", ms.At(i).Description())
					assert.Equal(t, "{reads}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("table")
					assert.True(t, ok)
					assert.Equal(t, "table-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("index")
					assert.True(t, ok)
					assert.Equal(t, "index-val", attrVal.Str())
				case "cockroachdb.jobs.count":
					assert.False(t, validatedMetrics["cockroachdb.jobs.count"], "Found a duplicate in the metrics slice: cockroachdb.jobs.count")
					validatedMetrics["cockroachdb.jobs.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of jobs by type and status.", ms.At(i).Description())
					assert.Equal(t, "{jobs}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("job_type")
					assert.True(t, ok)
					assert.Equal(t, "job_type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("status")
					assert.True(t, ok)
					assert.Equal(t, "status-val", attrVal.Str())
				case "cockroachdb.nodes.live":
					assert.False(t, validatedMetrics["cockroachdb.nodes.live"], "Found a duplicate in the metrics slice: cockroachdb.nodes.live")
					validatedMetrics["cockroachdb.nodes.live"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of live nodes. Not available on CockroachDB Serverless.", ms.At(i).Description())
					assert.Equal(t, "{nodes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.nodes.total":
					assert.False(t, validatedMetrics["cockroachdb.nodes.total"], "Found a duplicate in the metrics slice: cockroachdb.nodes.total")
					validatedMetrics["cockroachdb.nodes.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total number of nodes in the cluster. Not available on CockroachDB Serverless.", ms.At(i).Description())
					assert.Equal(t, "{nodes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.ranges.total":
					assert.False(t, validatedMetrics["cockroachdb.ranges.total"], "Found a duplicate in the metrics slice: cockroachdb.ranges.total")
					validatedMetrics["cockroachdb.ranges.total"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Total number of ranges in the cluster. Not available on CockroachDB Serverless.", ms.At(i).Description())
					assert.Equal(t, "{ranges}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.ranges.unavailable":
					assert.False(t, validatedMetrics["cockroachdb.ranges.unavailable"], "Found a duplicate in the metrics slice: cockroachdb.ranges.unavailable")
					validatedMetrics["cockroachdb.ranges.unavailable"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of unavailable ranges. Not available on CockroachDB Serverless.", ms.At(i).Description())
					assert.Equal(t, "{ranges}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.ranges.under_replicated":
					assert.False(t, validatedMetrics["cockroachdb.ranges.under_replicated"], "Found a duplicate in the metrics slice: cockroachdb.ranges.under_replicated")
					validatedMetrics["cockroachdb.ranges.under_replicated"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of under-replicated ranges. Not available on CockroachDB Serverless.", ms.At(i).Description())
					assert.Equal(t, "{ranges}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
				case "cockroachdb.schema_changes.active":
					assert.False(t, validatedMetrics["cockroachdb.schema_changes.active"], "Found a duplicate in the metrics slice: cockroachdb.schema_changes.active")
					validatedMetrics["cockroachdb.schema_changes.active"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of active schema changes.", ms.At(i).Description())
					assert.Equal(t, "{changes}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("table")
					assert.True(t, ok)
					assert.Equal(t, "table-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("change_type")
					assert.True(t, ok)
					assert.Equal(t, "change_type-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("state")
					assert.True(t, ok)
					assert.Equal(t, "state-val", attrVal.Str())
				case "cockroachdb.session.memory.allocated":
					assert.False(t, validatedMetrics["cockroachdb.session.memory.allocated"], "Found a duplicate in the metrics slice: cockroachdb.session.memory.allocated")
					validatedMetrics["cockroachdb.session.memory.allocated"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Memory allocated by a session.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("node_id")
					assert.True(t, ok)
					assert.Equal(t, "node_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.statement.bytes.read.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.bytes.read.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.bytes.read.mean")
					validatedMetrics["cockroachdb.statement.bytes.read.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average bytes read per statement execution.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.error.count":
					assert.False(t, validatedMetrics["cockroachdb.statement.error.count"], "Found a duplicate in the metrics slice: cockroachdb.statement.error.count")
					validatedMetrics["cockroachdb.statement.error.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of errors for a statement.", ms.At(i).Description())
					assert.Equal(t, "{errors}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("last_error_code")
					assert.True(t, ok)
					assert.Equal(t, "last_error_code-val", attrVal.Str())
				case "cockroachdb.statement.execution.count":
					assert.False(t, validatedMetrics["cockroachdb.statement.execution.count"], "Found a duplicate in the metrics slice: cockroachdb.statement.execution.count")
					validatedMetrics["cockroachdb.statement.execution.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of times a statement was executed.", ms.At(i).Description())
					assert.Equal(t, "{executions}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("statement_type")
					assert.True(t, ok)
					assert.Equal(t, "statement_type-val", attrVal.Str())
				case "cockroachdb.statement.latency.parse.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.latency.parse.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.latency.parse.mean")
					validatedMetrics["cockroachdb.statement.latency.parse.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average parsing latency for a statement.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.latency.plan.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.latency.plan.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.latency.plan.mean")
					validatedMetrics["cockroachdb.statement.latency.plan.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average planning latency for a statement.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.latency.run.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.latency.run.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.latency.run.mean")
					validatedMetrics["cockroachdb.statement.latency.run.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average execution latency for a statement.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.latency.service.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.latency.service.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.latency.service.mean")
					validatedMetrics["cockroachdb.statement.latency.service.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average service latency for a statement.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.retries.max":
					assert.False(t, validatedMetrics["cockroachdb.statement.retries.max"], "Found a duplicate in the metrics slice: cockroachdb.statement.retries.max")
					validatedMetrics["cockroachdb.statement.retries.max"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum number of retries for a statement.", ms.At(i).Description())
					assert.Equal(t, "{retries}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.rows.read.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.rows.read.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.rows.read.mean")
					validatedMetrics["cockroachdb.statement.rows.read.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average rows read per statement execution.", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.statement.rows.written.mean":
					assert.False(t, validatedMetrics["cockroachdb.statement.rows.written.mean"], "Found a duplicate in the metrics slice: cockroachdb.statement.rows.written.mean")
					validatedMetrics["cockroachdb.statement.rows.written.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average rows written per statement execution.", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("query")
					assert.True(t, ok)
					assert.Equal(t, "query-val", attrVal.Str())
				case "cockroachdb.table.contention.events":
					assert.False(t, validatedMetrics["cockroachdb.table.contention.events"], "Found a duplicate in the metrics slice: cockroachdb.table.contention.events")
					validatedMetrics["cockroachdb.table.contention.events"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of contention events on a table.", ms.At(i).Description())
					assert.Equal(t, "{events}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("schema")
					assert.True(t, ok)
					assert.Equal(t, "schema-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("table")
					assert.True(t, ok)
					assert.Equal(t, "table-val", attrVal.Str())
				case "cockroachdb.transaction.bytes.read.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.bytes.read.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.bytes.read.mean")
					validatedMetrics["cockroachdb.transaction.bytes.read.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average bytes read per transaction.", ms.At(i).Description())
					assert.Equal(t, "By", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.execution.count":
					assert.False(t, validatedMetrics["cockroachdb.transaction.execution.count"], "Found a duplicate in the metrics slice: cockroachdb.transaction.execution.count")
					validatedMetrics["cockroachdb.transaction.execution.count"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Number of times a transaction was executed.", ms.At(i).Description())
					assert.Equal(t, "{transactions}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.latency.commit.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.latency.commit.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.latency.commit.mean")
					validatedMetrics["cockroachdb.transaction.latency.commit.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average commit latency.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.latency.retry.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.latency.retry.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.latency.retry.mean")
					validatedMetrics["cockroachdb.transaction.latency.retry.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average retry latency.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.latency.service.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.latency.service.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.latency.service.mean")
					validatedMetrics["cockroachdb.transaction.latency.service.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average transaction service latency.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.retries.max":
					assert.False(t, validatedMetrics["cockroachdb.transaction.retries.max"], "Found a duplicate in the metrics slice: cockroachdb.transaction.retries.max")
					validatedMetrics["cockroachdb.transaction.retries.max"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Maximum number of retries for a transaction.", ms.At(i).Description())
					assert.Equal(t, "{retries}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.rows.read.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.rows.read.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.rows.read.mean")
					validatedMetrics["cockroachdb.transaction.rows.read.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average rows read per transaction.", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				case "cockroachdb.transaction.rows.written.mean":
					assert.False(t, validatedMetrics["cockroachdb.transaction.rows.written.mean"], "Found a duplicate in the metrics slice: cockroachdb.transaction.rows.written.mean")
					validatedMetrics["cockroachdb.transaction.rows.written.mean"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Average rows written per transaction.", ms.At(i).Description())
					assert.Equal(t, "{rows}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("fingerprint_id")
					assert.True(t, ok)
					assert.Equal(t, "fingerprint_id-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("app_name")
					assert.True(t, ok)
					assert.Equal(t, "app_name-val", attrVal.Str())
				}
			}
		})
	}
}
