// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"

	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CockroachdbClusterLocksCount:             MetricConfig{Enabled: true},
					CockroachdbClusterQueriesActive:          MetricConfig{Enabled: true},
					CockroachdbClusterSessionsActive:         MetricConfig{Enabled: true},
					CockroachdbClusterTransactionsActive:     MetricConfig{Enabled: true},
					CockroachdbContentionEventsTotal:         MetricConfig{Enabled: true},
					CockroachdbIndexContentionEvents:         MetricConfig{Enabled: true},
					CockroachdbIndexReadsTotal:               MetricConfig{Enabled: true},
					CockroachdbJobsCount:                     MetricConfig{Enabled: true},
					CockroachdbNodesLive:                     MetricConfig{Enabled: true},
					CockroachdbNodesTotal:                    MetricConfig{Enabled: true},
					CockroachdbRangesTotal:                   MetricConfig{Enabled: true},
					CockroachdbRangesUnavailable:             MetricConfig{Enabled: true},
					CockroachdbRangesUnderReplicated:         MetricConfig{Enabled: true},
					CockroachdbSchemaChangesActive:           MetricConfig{Enabled: true},
					CockroachdbSessionMemoryAllocated:        MetricConfig{Enabled: true},
					CockroachdbStatementBytesReadMean:        MetricConfig{Enabled: true},
					CockroachdbStatementErrorCount:           MetricConfig{Enabled: true},
					CockroachdbStatementExecutionCount:       MetricConfig{Enabled: true},
					CockroachdbStatementLatencyParseMean:     MetricConfig{Enabled: true},
					CockroachdbStatementLatencyPlanMean:      MetricConfig{Enabled: true},
					CockroachdbStatementLatencyRunMean:       MetricConfig{Enabled: true},
					CockroachdbStatementLatencyServiceMean:   MetricConfig{Enabled: true},
					CockroachdbStatementRetriesMax:           MetricConfig{Enabled: true},
					CockroachdbStatementRowsReadMean:         MetricConfig{Enabled: true},
					CockroachdbStatementRowsWrittenMean:      MetricConfig{Enabled: true},
					CockroachdbTableContentionEvents:         MetricConfig{Enabled: true},
					CockroachdbTransactionBytesReadMean:      MetricConfig{Enabled: true},
					CockroachdbTransactionExecutionCount:     MetricConfig{Enabled: true},
					CockroachdbTransactionLatencyCommitMean:  MetricConfig{Enabled: true},
					CockroachdbTransactionLatencyRetryMean:   MetricConfig{Enabled: true},
					CockroachdbTransactionLatencyServiceMean: MetricConfig{Enabled: true},
					CockroachdbTransactionRetriesMax:         MetricConfig{Enabled: true},
					CockroachdbTransactionRowsReadMean:       MetricConfig{Enabled: true},
					CockroachdbTransactionRowsWrittenMean:    MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					DbSystemName: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					CockroachdbClusterLocksCount:             MetricConfig{Enabled: false},
					CockroachdbClusterQueriesActive:          MetricConfig{Enabled: false},
					CockroachdbClusterSessionsActive:         MetricConfig{Enabled: false},
					CockroachdbClusterTransactionsActive:     MetricConfig{Enabled: false},
					CockroachdbContentionEventsTotal:         MetricConfig{Enabled: false},
					CockroachdbIndexContentionEvents:         MetricConfig{Enabled: false},
					CockroachdbIndexReadsTotal:               MetricConfig{Enabled: false},
					CockroachdbJobsCount:                     MetricConfig{Enabled: false},
					CockroachdbNodesLive:                     MetricConfig{Enabled: false},
					CockroachdbNodesTotal:                    MetricConfig{Enabled: false},
					CockroachdbRangesTotal:                   MetricConfig{Enabled: false},
					CockroachdbRangesUnavailable:             MetricConfig{Enabled: false},
					CockroachdbRangesUnderReplicated:         MetricConfig{Enabled: false},
					CockroachdbSchemaChangesActive:           MetricConfig{Enabled: false},
					CockroachdbSessionMemoryAllocated:        MetricConfig{Enabled: false},
					CockroachdbStatementBytesReadMean:        MetricConfig{Enabled: false},
					CockroachdbStatementErrorCount:           MetricConfig{Enabled: false},
					CockroachdbStatementExecutionCount:       MetricConfig{Enabled: false},
					CockroachdbStatementLatencyParseMean:     MetricConfig{Enabled: false},
					CockroachdbStatementLatencyPlanMean:      MetricConfig{Enabled: false},
					CockroachdbStatementLatencyRunMean:       MetricConfig{Enabled: false},
					CockroachdbStatementLatencyServiceMean:   MetricConfig{Enabled: false},
					CockroachdbStatementRetriesMax:           MetricConfig{Enabled: false},
					CockroachdbStatementRowsReadMean:         MetricConfig{Enabled: false},
					CockroachdbStatementRowsWrittenMean:      MetricConfig{Enabled: false},
					CockroachdbTableContentionEvents:         MetricConfig{Enabled: false},
					CockroachdbTransactionBytesReadMean:      MetricConfig{Enabled: false},
					CockroachdbTransactionExecutionCount:     MetricConfig{Enabled: false},
					CockroachdbTransactionLatencyCommitMean:  MetricConfig{Enabled: false},
					CockroachdbTransactionLatencyRetryMean:   MetricConfig{Enabled: false},
					CockroachdbTransactionLatencyServiceMean: MetricConfig{Enabled: false},
					CockroachdbTransactionRetriesMax:         MetricConfig{Enabled: false},
					CockroachdbTransactionRowsReadMean:       MetricConfig{Enabled: false},
					CockroachdbTransactionRowsWrittenMean:    MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					DbSystemName: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				DbSystemName: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				DbSystemName: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
