// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("cockroachdb")
	ScopeName = "github.com/npcomplete777/cockroachdb-receiver/cockroachreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
